### ISSUE TITLE
Error after worldborder

### ISSUE THREAD

**Issue by ZmBiUnicorn** [Kondee3/JustHomes#4]
[JustHomes] Task #401347 for JustHomes v1.19.0.2 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.HashMap.get(Object)" is null
        at me.kondi.JustHomes.Teleportation.TeleportPlayer$1.run(TeleportPlayer.java:37) ~[JustHomes-1.19.0.2.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-133]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1493) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1417) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1193) ~[paper-1.19.2.jar:git-Paper-133]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-133]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        
       
  I keep getting this warning after adding a world border and someone joins with a home placed outside the worldborder.
  it deleted their homes and constantly spams the warning.

**Comment by Kondee3** [comment]
Issue solved in new Update 1.20.1
